name: Build
on: [push]

defaults:
  run:
    working-directory: example/

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        id: flutter
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS application
        run: flutter build ios --no-codesign

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        id: flutter
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build Android application
        run: flutter build apk