name: Publish to pub.dev
on:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        id: flutter
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Publishing
        run: flutter pub publish